<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AAPreProcessor_WSWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/AAPreProcessor_WSWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/AAPreProcessor_WSWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://airalliance.org/">
    <import location="AAPreProcessor_WS.wsdl" namespace="http://airalliance.org/"/>
    <plnk:partnerLinkType name="AAPreProcessor_WSLinkType">
        <plnk:role name="AAPreProcessor_WSRole" portType="ns:AAPreProcessor_WS"/>
    </plnk:partnerLinkType>
</definitions>
