<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WestAir_WSWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WestAir_WSWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WestAir_WSWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://westair.airalliance.org/">
    <import location="WestAir_WS.wsdl" namespace="http://westair.airalliance.org/"/>
    <plnk:partnerLinkType name="WestAir_WSLinkType">
        <plnk:role name="WestAir_WSRole" portType="ns:WestAir_WS"/>
    </plnk:partnerLinkType>
</definitions>
